language: node_js
sudo: required
dist: trusty
node_js:
  - 10.15.3

notifications:
  email: false

before_script:
  - npm prune

script:
  - npm run clean
  - npm run deploy

branches:
  only:
    - master
    - develop

cache:
  directories:
    - $HOME/.npm

deploy:
  provider: script
  script: npm run deploy:travis
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  on:
    branch: master
