language: node_js
sudo: required
dist: trusty
node_js:
  - '10.15.3'

notifications:
  email: false

before_script:
  - 'git config --global user.name "liuliangsir"'
  - 'git config --global user.email "2269305724@qq.com"'
  - npm prune

script:
  - npm run clean
  - npm run deploy

branches:
  only:
    - master
    - /^greenkeeper\/.*$/

cache:
  directories:
    - $HOME/.npm

deploy:
  provider: script
  script: npm run deploy:travis
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  on:
    branch: master
